#!/usr/bin/env node
/**
 * Sync src/version.ts with package.json version.
 * Run as: node scripts/sync-version.js
 * Or via npm: npm run sync-version
 */
const { readFileSync, writeFileSync } = require('fs');
const { join } = require('path');

const root = join(__dirname, '..');
const pkgPath = join(root, 'package.json');
const versionPath = join(root, 'src', 'version.ts');

try {
  const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
  const version = pkg.version;

  if (!version || typeof version !== 'string') {
    console.error('❌ Invalid version in package.json');
    process.exit(1);
  }

  const content = `// Auto-generated by scripts/sync-version.js — do not edit manually\nexport const VERSION = '${version}';\n`;

  writeFileSync(versionPath, content, 'utf8');
  console.log(`✅ Synced version: ${version}`);
} catch (err) {
  console.error('❌ sync-version failed:', err.message);
  process.exit(1);
}
